### PR TITLE
Allow using CocoaPods to install the library

### PR DESCRIPTION
**Pull request by jasperblues**
- Moved DemoViewController.{h,mm} from the main folder to the demo folder. 
- Create a .podspec file and tested it. Example of usage: 

======== Example Podfile ======== 
platform :ios, '5.0'

pod 'ZBarSDK'
pod "QR-Code-Encoder-for-Objective-C", :git => "https://github.com/jasperblues/QR-Code-Encoder-for-Objective-C.git"
- I would like to push the .podspec to the main CocoaPods spec repo. . This allows using the short-hand style, like with ZBarSDK above. . . before I do this:  It would be better to have a tag to refer to as the version.

### CODE REVIEW

**Comment by johnrickman** [comment]
Does this library work with CocoaPods?

**Comment by jasperblues** [comment]
Yes, of course. 

The pull request includes the working podspec (which I set up for a recent project). You can install the library from CocoaPods by creating a podfile with the contents: 

pod "QR-Code-Encoder-for-Objective-C", :git => "https://github.com/jasperblues/QR-Code-Encoder-for-Objective-C.git"

(after the pull request the URL will be this repo's URL). 

However, its better to push the library to the main CocoaPods repo . . . after this you can install it with simply: 

pod 'QR-Code-Encoder-for-Objective-C'

**Comment by skull-squadron** [comment]
:+1:

**Comment by myang-git** [comment]
good job!

**Comment by skull-squadron** [comment]
:beers: 

Btw, I'm porting the QR coder to C99.  This does two things... Makes it portable (could extract out for embedded work) and eliminates the .mm.

**Comment by jasperblues** [comment]
The .mm doesn't bother me, but I think it will help a lot of Objective-C developers.

**Comment by jasperblues** [comment]
There's one final task, before I can contribute the .podspec file to the main CoocaPods repo, and that is to create a tag (eg 1.0.0) . . 

Would you be able to do that? 

git tag 1.0.0
git push origin 1.0.0

If you modify the podspec to match the one I push to master, like so - would be good to . 

(Change :commit to :tag)

Pod::Spec.new do |spec|
    spec.name = 'QR-Code-Encoder-for-Objective-C'
    spec.version = '1.0.0'
    spec.license = 'Apache2.0'
    spec.summary = 'An implementation of QR code encoder for Objective-C ported from Psytec library.'
    spec.homepage = 'https://github.com/myang-git/QR-Code-Encoder-for-Objective-C'
    spec.author = { 'Ming Yang' => 'myang.git@gmail.com' }
    spec.source = { :git => 'https://github.com/myang-git/QR-Code-Encoder-for-Objective-C.git',
        :tag => '1.0.0' }
    spec.source_files = 'QRCodeEncoderObjectiveCAtGithub/*_/_.{h,m,mm,cpp}'
    spec.requires_arc = false
end

This is not strictly necessary, but would be better.

**Comment by myang-git** [comment]
Tag created. Podspec updated as well.

**Comment by jasperblues** [comment]
I've pushed an (updated) Spec to the main CocoaPods repo. . There are two changes required to make this one match: 
1. Add platform = :ios <- required because of a direct dependency on UIKit. To support both osx and ios the lib would need minor modifications. 
2. Change :commit to :tag. 

Updated Spec shown below, please correct local copy. 

Pod::Spec.new do |spec|
    spec.name         = 'QR-Code-Encoder-for-Objective-C'
    spec.platform     = :ios
    spec.version      = '1.0.0'
    spec.license      = 'Apache2.0'
    spec.summary      = 'An implementation of QR code encoder for Objective-C ported from Psytec library.'
    spec.homepage     = 'https://github.com/myang-git/QR-Code-Encoder-for-Objective-C'
    spec.author       = { 'Ming Yang' => 'myang.git@gmail.com' }
    spec.source       = { :git => 'https://github.com/myang-git/QR-Code-Encoder-for-Objective-C.git',
        :tag => '1.0.0' }
    spec.source_files = 'QRCodeEncoderObjectiveCAtGithub/*_/_.{h,m,mm,cpp}'
    spec.requires_arc = false
end

**Comment by skull-squadron** [comment]
Oh yeah! :beers:

 create mode 100644 PRAugmentedReality/2.0.0/PRAugmentedReality.podspec
 create mode 100644 PSUpdateApp/1.0.6/PSUpdateApp.podspec
 create mode 100644 ParseModel/1.1.0/ParseModel.podspec
**create mode 100644 QR-Code-Encoder-for-Objective-C/1.0.0/QR-Code-Encoder-for-Objective-C.podspec**
 create mode 100644 REActivityViewController/1.6.1/REActivityViewController.podspec
 create mode 100644 RMSwipeTableViewCell/0.3/RMSwipeTableViewCell.podspec
 create mode 100644 SDJSONPrettyPrint/0.0.1/SDJSONPrettyPrint.podspec
 create mode 100644 SHXMLParser/1.1.0/SHXMLParser.podspec
 create mode 100644 SocketShuttle/0.3/SocketShuttle.podspec

**Pull request merged**
