### PR TITLE
C++ -> Portable C99 &| C++

### PR DESCRIPTION
**Pull request by skull-squadron**
Needs feedback obviously.

### CODE REVIEW

**Comment by skull-squadron** [comment]
In reference to #25

**Comment by skull-squadron** [comment]
The QR encoder functions really need unit tests.

**Comment by skull-squadron** [comment]
The QR Encoder itself was converted to Doom 3-style code conventions.

The file wasted much too much vertical space.

Other changes are to keep consistency.

**Comment by skull-squadron** [comment]
simulator_screenshot
decoded_screenshot

**Comment by skull-squadron** [comment]
Objective-C version

img

[Decodes the same](http://zxing.org/w/decode?u=http%3A%2F%2Fcontent.screencast.com%2Fusers%2Fzxcvxzcvxcv%2Ffolders%2FJing%2Fmedia%2F66134415-bcdf-4f87-8d6e-fefa8ec436f5%2F00000102.png)

**Comment by skull-squadron** [comment]
Above test is anecdotal.  This isn't as good as unit-testing (encode each of different types of code data, error correction and # of modules).

**Comment by myang-git** [comment]
This is great. Good job! I will test it as well

**Pull request closed without merging**
